name: TestAndDeploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm ci

      - name: test
        run: |
          npm test
          npm run test:e2e
          npm run test:cov

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            whoami
            cd ${{ secrets.DEPLOY_TARGET }}
            git pull
            npm ci --silent
            npm run build
            pm2 stop "colonie"
            pm2 start npm --name "colonie" -- start

    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
